### ISSUE TITLE
Fix mangling of input to the action

### ISSUE THREAD

**Issue by harigopal** [pupilfirst/ai-review-action#1]
During testing, it was noticed that the prompt inputs configured for the action are being processed without proper line breaks when the request is finally sent to ChatGPT. This is _likely_ happening because the input is being passed through environment variables, where line breaks are unacceptable. An alternative method that doesn't involve this mangling will be required.

An option that occurs to me is to avoid using Docker (which is why env vars are being used), and instead set up a Ruby env for the action and run the script directly using input fed unalterted into the Ruby script using some method... maybe simply dumping the input as JSON into a file before executing the Ruby script.

**Comment by yash-learner** [comment]
FYI:

We also need to replace `>` with `|` in action config in targets because `>` will remove the line breaks

https://chat.openai.com/share/b7ef7836-a282-4e40-9efd-e0c333d76a5b
